name: autotest
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.9
      - name: Set up Poetry
        uses: abatilo/actions-poetry@master
        with:
          poetry-version: 1.1.12
      - name: Install dependencies
        run: |
          poetry install
      - name: Lint with flake8m
        run: |
          # stop the build if there are Python syntax errors or undefined names
          poetry run flake8 . --count --exit-zero --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          poetry run pytest
